// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"
)

type DailyTodo struct {
	ID          int64
	Name        string
	Iscomplete  bool
	Priority    int64
	DateCreated sql.NullTime
}

type Todo struct {
	ID          int64
	Name        string
	Iscomplete  bool
	Priority    int64
	DateCreated sql.NullTime
	DueDate     time.Time
}
